build-development:
  stage: build
  environment:
    name: development
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always
  image: docker:latest
  script:
    - docker build -t $CI_REGISTRY_IMAGE:development -f ./src/YOOTEK.Web.Host/Dockerfile ./src
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:development

deploy-development:
  stage: deploy
  environment:
    name: development
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/gitlab
    - chmod 700 ~/.ssh/gitlab
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/gitlab
    - ssh-keyscan -H "$REMOTE_HOST" >> ~/.ssh/known_hosts
  script:
    - cat $DEPLOY_SCRIPT > deploy.sh
    - chmod +x ./deploy.sh
    - sh ./deploy.sh

build-production:
  stage: build
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
  image: docker:latest
  script:
    - docker build -t $CI_REGISTRY_IMAGE:production -f ./src/YOOTEK.Web.Host/Dockerfile ./src
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:production